### ISSUE TITLE
Upgrade to support handlebars 2.0

### ISSUE THREAD

**Issue by dgaus** [toranb/django-ember-precompile#9]
Hi, would you consider making a new release to support Handlebars 2.0? The changes necesary are pretty minimal and can be found in https://github.com/lewtds/django-ember-precompile . Thanks!

**Comment by toranb** [comment]
You know it! If it's working for you submit a PR and I'll pull it in. What version of ember are you using then?

**Comment by dgaus** [comment]
Well, it worked perfectly for Ember 1.09, but in 1.10 they changed Handlebars for HTMLbars and it predictebly it doesn't work anymore.

**Comment by toranb** [comment]
I'll lose out this issue and pull in your other PR !
